# Generated by Django 3.2 on 2021-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('description', models.CharField(max_length=300, verbose_name='Описание заявки')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Почта')),
                ('number', models.IntegerField(max_length=150, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Формы заявки',
                'verbose_name_plural': 'Форма заявки',
            },
        ),
    ]
