# Generated by Django 3.2 on 2021-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
